# Generated by Django 4.2.1 on 2026-03-23 13:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import rent_ms_utils.RentalUtils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rent_ms_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('owner_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to='rent_ms_accounts.usersprofiles')),
            ],
            options={
                'verbose_name_plural': '01. Houses',
                'db_table': 'houses',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('medium', models.CharField(choices=[('Sms', 'Sms'), ('Email', 'Email')], max_length=100, unique=True)),
                ('payload', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Failed', 'Failed')], default='Pending', max_length=255)),
                ('attempts', models.CharField(max_length=255)),
                ('error_message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': '03. Notifications',
                'db_table': 'notifications',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('regional_unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reginal_name', models.CharField(default='', max_length=9000)),
                ('reginal_postcode', models.CharField(default='', max_length=9000)),
                ('reginal_napa_id', models.CharField(default='', max_length=9000)),
                ('reginal_code', models.CharField(blank=True, default='', max_length=9000, null=True)),
                ('regional_createddate', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': '05. Regions',
                'db_table': 'regions',
                'ordering': ['-primary_key'],
            },
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('renter_title', models.CharField(blank=True, default='', max_length=9000, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('nida_number', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': '02. Renters',
                'db_table': 'renters',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HouseRental',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reference_no', models.CharField(default=rent_ms_utils.RentalUtils.RentalUtils.generate_contract_reference, max_length=20, unique=True)),
                ('duration', models.CharField(choices=[(3, 'Three Months'), (6, 'Six Months'), (12, 'One Year')], default=3, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('auto_renew', models.BooleanField(default=False)),
                ('notice_period_days', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated')], default='PENDING', max_length=50)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_contracts', to='rent_ms_settings.house')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_contracts', to='rent_ms_accounts.usersprofiles')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter_contracts', to='rent_ms_settings.renter')),
            ],
            options={
                'verbose_name_plural': '04. House Rentals',
                'db_table': 'house_rentals',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('district_unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('district_name', models.CharField(default='', max_length=9000)),
                ('district_postcode', models.CharField(default='', max_length=9000)),
                ('district_napa_id', models.CharField(default='', max_length=9000)),
                ('district_createddate', models.DateField(auto_now_add=True, null=True)),
                ('district_parent_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rent_ms_settings.region')),
            ],
            options={
                'verbose_name_plural': '06. Districts',
                'db_table': 'districts',
                'ordering': ['-primary_key'],
            },
        ),
    ]
