# Generated by Django 4.2.1 on 2026-04-09 17:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rent_ms_accounts', '0002_forgotpasswordrequestusers_request_created_at'),
        ('rent_ms_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('MobileMoney', 'Mobile Money'), ('BankTransfer', 'Bank Transfer')], max_length=50)),
                ('payment_type', models.CharField(choices=[('Full', 'Full'), ('Partial', 'Partial')], max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], default='Completed', max_length=20)),
                ('reference_no', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rent_ms_accounts.usersprofiles')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rent_ms_settings.houserental')),
            ],
            options={
                'verbose_name_plural': '07. Rental Payments',
                'db_table': 'rental_payments',
                'ordering': ['-id'],
            },
        ),
    ]
