# Generated by Django 4.2.1 on 2026-03-23 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersProfiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('profile_type', models.CharField(blank=True, choices=[('ADMIN_PROFILE', 'ADMIN_PROFILE'), ('NORMAL_PROFILE', 'NORMAL_PROFILE')], max_length=9000, null=True)),
                ('profile_level', models.CharField(blank=True, choices=[('REGION', 'REGION'), ('DISTRICT', 'DISTRICT')], max_length=9000, null=True)),
                ('profile_phone', models.CharField(blank=True, default='', max_length=9000, null=True)),
                ('profile_title', models.CharField(blank=True, default='', max_length=9000, null=True)),
                ('profile_photo', models.CharField(blank=True, default='/profiles/user_profile.png', max_length=600, null=True)),
                ('profile_gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=100, null=True)),
                ('profile_is_active', models.BooleanField(default=True)),
                ('profile_createddate', models.DateField(auto_now_add=True)),
                ('profile_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'USER PROFILES',
                'db_table': 'user_profiles',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ForgotPasswordRequestUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_token', models.CharField(default=None, editable=False, max_length=300)),
                ('request_is_used', models.BooleanField(default=False)),
                ('request_is_active', models.BooleanField(default=True)),
                ('request_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'FORGOT PASSWORD REQUESTS',
                'db_table': 'forgot_password_request',
                'ordering': ['-id'],
            },
        ),
    ]
