# Generated by Django 4.2.1 on 2026-03-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_ms_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgotpasswordrequestusers',
            name='request_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
