# Generated by Django 4.2.1 on 2026-03-23 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('permission_unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('permission_name', models.CharField(default='', max_length=9000)),
                ('permission_code', models.CharField(default='', max_length=9000)),
                ('permission_createddate', models.DateField(auto_now_add=True)),
                ('permission_createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permission_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'USER PERMISSIONS',
                'db_table': 'user_permissions',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('role_name', models.CharField(default='', max_length=9000)),
                ('role_description', models.CharField(default='', max_length=9000)),
                ('role_is_active', models.BooleanField(default=True)),
                ('role_createddate', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'USER ROLES',
                'db_table': 'user_roles',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UsersWithRoles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_with_role_unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_with_role_createddate', models.DateField(auto_now_add=True)),
                ('user_with_role_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_name', to='rent_ms_uaa.userroles')),
                ('user_with_role_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'USERS WITH ROLES',
                'db_table': 'user_with_roles',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UserRolesWithPermissions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_with_permission_unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('permission_read_only', models.BooleanField(default=True)),
                ('role_with_permission_createddate', models.DateField(auto_now_add=True)),
                ('role_with_permission_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_with_permission_permission', to='rent_ms_uaa.userpermissions')),
                ('role_with_permission_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_with_permission_role', to='rent_ms_uaa.userroles')),
            ],
            options={
                'verbose_name_plural': 'ROLES WITH PERMISSIONS',
                'db_table': 'user_role_with_permissions',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UserPermissionsGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('permission_group_unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('permission_group_name', models.CharField(default='', max_length=9000)),
                ('permission_group_is_global', models.BooleanField(default=False)),
                ('permission_group_description', models.CharField(default='', max_length=600, null=True)),
                ('permission_group_createddate', models.DateField(auto_now_add=True)),
                ('permission_group_createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_group_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PERMISSIONS GROUP',
                'db_table': 'user_permissions_group',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='permission_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_group', to='rent_ms_uaa.userpermissionsgroup'),
        ),
    ]
