# Generated by Django 4.2.1 on 2026-03-23 13:24

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentMsSms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(blank=True, choices=[('ENROUTE', 'ENROUTE'), ('DELIVERED', 'DELIVERED'), ('ACCEPTED', 'ACCEPTED')], max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('third_party_ref', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('message_to_user', models.CharField(blank=True, max_length=255, null=True)),
                ('user_phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('smscId', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': '01. Rent Ms Sms',
                'db_table': 'sms',
                'ordering': ['-id'],
            },
        ),
    ]
