
"""
Django settings for rent_ms_backend project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from dotenv import load_dotenv
from dotenv import dotenv_values
from pathlib import Path

load_dotenv()

config = dotenv_values(".env")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*vqxoy-w(x4zc6%i&ld(y-_1u708%xu(5m8w=r7nkcn0qy%m5c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
USE_TZ = True

ALLOWED_HOSTS = ["*"]

GOOGLE_OAUTH_CLIENT_ID = os.environ.get('GOOGLE_OAUTH_CLIENT_ID')
if not GOOGLE_OAUTH_CLIENT_ID:
    raise ValueError(
        'GOOGLE_OAUTH_CLIENT_ID is missing.'
        'Have you put it in a file at core/.env ?'
    )



TWILIO_ACCOUNT_SID =  os.environ.get('MY_ACCOUNT_SID')
TWILIO_AUTH_TOKEN =  os.environ.get('TWILIO_AUTH_TOKEN')
TWILIO_NUMBER =  os.environ.get('MY_TWILIO_NUMBER')
SMS_BROADCAST_TO_NUMBERS = [ 
  '+255766577780'
]

INSTALLED_APPS = [
    # Custom Application,
    'rent_ms_accounts',
    'rent_ms_settings',
    'rent_ms_report',
    'rent_ms_uaa',
    'rent_ms_file_server',
    'rent_ms_payment',
    'rent_ms_sms',
    

    # Custom Libraries
    'graphene_django',
    'provider',
    'provider.oauth2',
    'corsheaders',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rent_ms_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'rent_ms_backend_html')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rent_ms_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

DATABASES = {
   'default': {
       'ENGINE': 'django.db.backends.postgresql',
       'NAME': config['DATABASE_NAME'],
       'USER': config['DATABASE_USER'],
       'PASSWORD': config['DATABASE_PASSWORD'],
       'HOST': config['DATABASE_HOST'],
       'PORT': config['DATABASE_PORT'],
   }
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/rent_ms_static/'
MEDIA_ROOT = '/rent_ms_media/'
STATIC_ROOT = os.path.join(BASE_DIR, "rent_ms_static") 

MEDIA_ROOT = os.path.join(BASE_DIR, 'rent_ms_media')
MEDIA_URL = '/rent_ms_media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CUSTOM SETTINGS

GRAPHENE = {
    'SCHEMA': 'rent_ms_backend.main_schema.schema'
}


# CORSHEADERS
CORS_ALLOW_ALL_ORIGINS = True
CSRF_TRUSTED_ORIGINS = ['http://82.25.119.147:8000']
CSRF_TRUSTED_ORIGINS = ['http://82.25.119.147:8000']
CORS_ALLOWED_ORIGINS = [
    "http://82.25.119.147:8000",
    "http://127.0.0.1",
]

# EMAIL CONFIGURATIONS
# EMAIL_HOST = config['EMAIL_HOST']
# EMAIL_PASSWORD = config['EMAIL_PASSWORD']
# EMAIL_USER = config['EMAIL_USER']
# EMAIL_PORT = config['EMAIL_PORT']
# EMAIL_USE_SSL = config['EMAIL_USE_SSL']
# EMAIL_USE_TLS = config['EMAIL_USE_TLS']
# DEFAULT_FROM_EMAIL = config['DEFAULT_FROM_EMAIL']
# EMAIL_SSL_VERIFICATION = False

# We need these lines below to allow the Google sign in popup to work.
SECURE_REFERRER_POLICY = 'no-referrer-when-downgrade'
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"

